#!/usr/bin/env bash

deploy() {
    export FLASK_ENV=production
    gunicorn -w 2 --bind=0.0.0.0:6969 "home_service:create_app()"
}


usage() { printf "%s" "\
Home service is a simple IoT server that allows for configuration

Usage: home-service [options] [command]

Options:
    --version, -v      Get version info and exit
    --help, -h         Print this message and exit

Commands:
    deploy, d          Start the home service server

"
exit 1
}

get_version() {
    version=$(python3 -c "import home_service; print(home_service.__version__)")
    echo $version
    exit 1
}

get_args() {
    while [[ "$1" ]]; do
        case $1 in
            "--version" | "-v") get_version ;;
            "--help" | "-h") usage ;;
            "deploy" | "d") deploy ;;
        esac
        shift
    done
}

main() {

    if [[ $# == 0 ]]; then
        usage
    else
        get_args "$1"
    fi

}

main "$@"
